### ISSUE TITLE
GET_MY_SUBJECTS could return an empty data object if no subjects in the DB at startup.

### ISSUE THREAD

**Issue by teenkevo** [teenkevo/learn-app#2]
* Inside the subjectInfo page we might need a check for an empty data object might be returned by the `GET_MY_SUBJECTS` query before using it in the `.map` function by 

Changing this 

```javascript
const subjectInfoCard = data.getMySubjects.map((subject) => {...}
````

to this 
```javascript
const subjectInfoCard = (data && data.getMySubjects.map((subject) => {...})
````

* Also just a small typo on function name `SubectInfoPage` and its default export `export default SubectInfoPage`. 
 
* The other main issue why the app failed to start is due to expired `Neo4j` credentials in the `.env` file received. 

```javascript
import React from "react";
import { GET_MY_SUBJECTS } from "../../utils/graphql";
import { useQuery } from "@apollo/react-hooks";
import { Card, Divider, Grid } from "@material-ui/core";
import Header from "../../components/Header/Header";
import SubjectContent from "../../components/SubjectContent/SubjectContent";
import SideCard from "../../components/SideCard/SideCard";

function activeRoute(routeName) {
  return window.location.href.indexOf(routeName) > -1 ? true : false;
}

function SubjectInfoPage() {
  const { loading, error, data } = useQuery(GET_MY_SUBJECTS);

  // FIXME: If no subject exists the code below would fail(.map of undefined)
  // FIXME: If GQL server doesnt respond on startup to the query, app wouldn't start 

  const subjectInfoCard = (data && data.getMySubjects.map((subject) => {
    if (activeRoute("/student/" + subject.title)) {
      return (
        <div>
          <Card>
            <Header title={subject.title} year={subject.year} />
            <Divider />
          </Card>
          <Grid
            container
            spacing={2}
            style={{ margin: "auto", padding: "10px" }}
          >
            <Grid item xs={12} md={12} lg={9}>
              <SubjectContent />
            </Grid>
            <Grid item xs={12} md={12} lg={3}>
              <SideCard />
            </Grid>
          </Grid>
        </div>
      );
    } else {
      return; // IMPLEMENT A TRY CATCH BLOCK FOR THE LOGIC IN THIS MAP AND IF
    }
  }));

  return <div>{subjectInfoCard}</div>;
}

export default SubjectInfoPage;
```

**Comment by Shghazy** [comment]
1. SubjectInfoPage cannot possible be empty. It gets its data from the created subject.
2. SubjectsPage, on the other hand, is what you might have meant. In this case, there is no problem with the database being empty with the current code. I have restarted neo4j Sandbox recently and it works fine. It renders a page with only the CreatorCard button. Hence there is no need to implement `// FIXME: If no subject exists the code below would fail(.map of undefined)` as the .map does not fail in that case. 
3. Yesterday you had the old neo4j credentials in your `.env`, this always breaks the app. I completely missed that!! I should have given you the new credentials. But I believe we should implement an error for the database connection. 
4. For `// FIXME: If GQL server doesnt respond on startup to the query, app wouldn't start`, this is similar to the database connection problem. If the server is not running or the database is unable to connect, only an Error word shows. We need to implement a more descriptive error logic for both the GQL and the database error.
5. Noted regarding the typo. Will make a commit shortly with the fixed typo. 
6. I am now trying to run the app, however, there seems to be a new problem:
`Access to fetch at 'http://localhost:5000/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
I believe it can be easily solved by adding http://localhost:3000 to the following field in Auth0:

![Capture](https://user-images.githubusercontent.com/71067972/108614772-70b4a200-73f5-11eb-98e4-b993249f5373.PNG)

However, my account does not have access to perform this change. Please add it in soon and let me know when you have done so. Also, please resend me the JWT_SECRET.

![Capture2](https://user-images.githubusercontent.com/71067972/108614782-81651800-73f5-11eb-9217-8b6a8a76b6d0.PNG)

And simultaneously, the terminal is showing `UnauthorizedError: jwt malformed`
When checking the headers, the token is indeed malformed showing `Authorization: Bearer 2-SlOXvCZ630GtNgqakIHfymi_0fVy_R` only.

**Comment by teenkevo** [comment]
1. Makes sense, yeah totally meant the subjectsPage, the `data &&` check might still be a good idea before any logic with that returned data.
2. Yes, the .env credentials were my grave.
3. Not a good idea to inject in CORS waivers manually in the front end via the header `Access-Control-Allow-Origin`. Front end `localhost:3000` is natively is not allowed to request sources from anything that is not `localhost:3000*`, which in this case is `localhost:5000\graphql`. This issue is better solved server side by wrapping the express app in the `cors` middleware i.e. `app.use(cors())`
4. Let me add localhost to allowed origins (CORS) on Auth0 right away. 
5. Will send you an updated .env in ur email with the old secret. It hasn't changed.
